In [1]:
## Current path display

import os
current_path = os.getcwd()
print(current_path)

D:\05_Projekte\04_Research\08_ManuBrain\01_Lab\Demo-Cell-Classification\02_Preprocessing

robot tag:
    * It seems to be that the gripper has as tag "546"

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Functions

In [3]:
# return tag from data
def fc_tag (data,index):
    return data.at[index,'d'].split('=')[2] # [2] equivalent a tag column data en txt file

# update tag in main table
def fc_tag_update(data, tag):
    for i in range(len(tag)):
        i = i + 1 
        data = data.replace({'PrimaryKey':i}, fc_tag(tag,i), regex = False)
    return data

## Paths from data set

In [4]:
date = 200924
uc_num = 1

path = str(date) + '/use_case' + str(uc_num)

# Conveyor_belt
path_data_conv = '../01_Data/' + path + '/Conveyor Speed/DataLogger.csv'
path_tag_conv = '../01_Data/' + path + '/Conveyor Speed/tagconfig.txt'

# Gate
path_data_gate = '../01_Data/' + path + '/Gate/DataLogger.csv'
path_tag_gate = '../01_Data/' + path + '/Gate/tagconfig.txt'

# Quality_Control
path_data_qc = '../01_Data/' + path + '/Quality Control/DataLogger.csv'
path_tag_qc = '../01_Data/' + path + '/Quality Control/tagconfig.txt'

# Robot_Position
path_data_rp = '../01_Data/' + path + '/Robot Position/DataLogger.csv'
path_tag_rp = '../01_Data/' + path + '/Robot Position/tagconfig.txt'

# Store
path_data_st = '../01_Data/' + path + '/Store/DataLogger.csv'
path_tag_st = '../01_Data/' + path + '/Store/tagconfig.txt'

# Processed data

path_data_save = '../01_Data/' + path + '/Processed/'
path_sample_save = '../01_Data/' + path + '/Processed/Samples/'

## Import data from csv

In [5]:
# Conveyor_belt
data_conv =  pd.read_csv(path_data_conv, delimiter = ',')
#df_conv = pd.DataFrame(pd.read_csv(path_data_conv, delimiter = ','))

# Gate
data_gate =  pd.read_csv(path_data_gate, delimiter = ',')
#df_gate = pd.DataFrame(pd.read_csv(path_data_gate, delimiter = ','))

# Quality_Control
data_qc =  pd.read_csv(path_data_qc, delimiter = ',')
#df_qc = pd.DataFrame(pd.read_csv(path_data_qc, delimiter = ','))

# Robot_Position
data_rp =  pd.read_csv(path_data_rp, delimiter = ',')
#df_rp = pd.DataFrame(pd.read_csv(path_data_rp, delimiter = ','))

# Store
data_st =  pd.read_csv(path_data_st, delimiter = ',')
#df_st = pd.DataFrame(pd.read_csv(path_data_st, delimiter = ','))

## Import data tags

In [6]:
# Conveyor_belt
tag_conv =  pd.read_fwf(path_tag_conv, sep=" ", header=None, names=['a','b','c','d'])
tag_conv = tag_conv.drop([0]) # delete first row (trash)

# Gate
tag_gate =  pd.read_fwf(path_tag_gate, sep=" ", header=None, names=['a','b','c','d'])
tag_gate = tag_gate.drop([0]) # delete first row (trash)

# Quality_Control
tag_qc =  pd.read_fwf(path_tag_qc, sep=" ", header=None, names=['a','b','c','d'])
tag_qc = tag_qc.drop([0]) # delete first row (trash)

# Robot_Position
tag_rp =  pd.read_fwf(path_tag_rp, sep=" ", header=None, names=['a','b','c','d'])
tag_rp = tag_rp.drop([0]) # delete first row (trash)

# Robot_Position
tag_st =  pd.read_fwf(path_tag_st, sep=" ", header=None, names=['a','b','c','d'])
tag_st = tag_st.drop([0]) # delete first row (trash)

## Update tags

In [7]:
# Conveyor_belt
data_conv = fc_tag_update(data_conv, tag_conv)

# Gate
data_gate = fc_tag_update(data_gate, tag_gate)

# Quality_Control
data_qc = fc_tag_update(data_qc, tag_qc)

# Robot_Position
data_rp = fc_tag_update(data_rp, tag_rp)

# Store
data_st = fc_tag_update(data_st, tag_st)

In [8]:
data_conv

,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp
0,27,0x0004,300,0x00000000,2020-09-24T10:34:04.602Z,2020-09-24T10:34:04.602Z
1,28,0x0004,363,0x00000000,2020-09-24T10:34:04.603Z,2020-09-24T10:34:04.603Z
2,29,0x0004,380,0x00000000,2020-09-24T10:34:04.603Z,2020-09-24T10:34:04.603Z
3,27,0x0004,300,0x002f0000,2020-09-24T10:54:04.852Z,2020-09-24T10:54:04.852Z
4,27,0x0004,300,0x00000000,2020-09-24T10:54:05.102Z,2020-09-24T10:54:05.102Z
5,28,0x0004,363,0x002f0000,2020-09-24T10:54:04.853Z,2020-09-24T10:54:04.853Z
6,28,0x0004,363,0x00000000,2020-09-24T10:54:05.103Z,2020-09-24T10:54:05.103Z
7,29,0x0004,380,0x002f0000,2020-09-24T10:54:04.853Z,2020-09-24T10:54:04.853Z
8,29,0x0004,380,0x00000000,2020-09-24T10:54:05.106Z,2020-09-24T10:54:05.106Z

In [9]:
data_gate

,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp
0,Position,0x000b,0.2,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z
1,Position,0x000b,0.2,0x00000000,2020-09-24T10:32:41.607Z,2020-09-24T10:32:41.607Z
2,Speed,0x000b,0,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z
3,Speed,0x000b,0,0x00000000,2020-09-24T10:32:41.607Z,2020-09-24T10:32:41.607Z
4,Safe,0x0001,true,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z
...,...,...,...,...,...,...
20287,Position,0x000b,49.2,0x00000000,2020-09-24T11:07:09.807Z,2020-09-24T11:07:09.807Z
20288,Speed,0x000b,-40,0x00000000,2020-09-24T11:07:09.507Z,2020-09-24T11:07:09.507Z
20289,Speed,0x000b,-40,0x00000000,2020-09-24T11:07:09.807Z,2020-09-24T11:07:09.807Z
20290,Safe,0x0001,false,0x00000000,2020-09-24T11:07:09.507Z,2020-09-24T11:07:09.507Z
20291,Safe,0x0001,false,0x00000000,2020-09-24T11:07:09.807Z,2020-09-24T11:07:09.807Z

In [10]:
data_qc

,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp
0,DistanceAbs,0x000b,0.000000,0x00000000,2020-09-24T10:32:44.966Z,2020-09-24T10:32:44.966Z
1,DistanceAbs,0x000b,0.000000,0x00000000,2020-09-24T10:32:45.267Z,2020-09-24T10:32:45.267Z
2,DistanceX,0x000b,0.000000,0x00000000,2020-09-24T10:32:44.967Z,2020-09-24T10:32:44.967Z
3,DistanceX,0x000b,0.000000,0x00000000,2020-09-24T10:32:45.267Z,2020-09-24T10:32:45.267Z
4,DistanceY,0x000b,0.000000,0x00000000,2020-09-24T10:32:44.967Z,2020-09-24T10:32:44.967Z
...,...,...,...,...,...,...
27019,DistanceX,0x000b,0.433815,0x00000000,2020-09-24T11:07:11.667Z,2020-09-24T11:07:11.667Z
27020,DistanceY,0x000b,0.860215,0x00000000,2020-09-24T11:07:11.367Z,2020-09-24T11:07:11.367Z
27021,DistanceY,0x000b,0.860215,0x00000000,2020-09-24T11:07:11.667Z,2020-09-24T11:07:11.667Z
27022,ResultCode,0x0006,0.000000,0x00000000,2020-09-24T11:07:11.367Z,2020-09-24T11:07:11.367Z
27023,ResultCode,0x0006,0.000000,0x00000000,2020-09-24T11:07:11.667Z,2020-09-24T11:07:11.667Z

In [11]:
data_rp

,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp
0,527,0x0007,1050942561,0x00000000,2020-09-24T10:33:30.605Z,2020-09-24T10:33:30.605Z
1,527,0x0007,1050942348,0x00000000,2020-09-24T10:33:30.853Z,2020-09-24T10:33:30.853Z
2,528,0x0007,3188278379,0x00000000,2020-09-24T10:33:30.605Z,2020-09-24T10:33:30.605Z
3,528,0x0007,3188277355,0x00000000,2020-09-24T10:33:30.855Z,2020-09-24T10:33:30.855Z
4,529,0x0007,1051705058,0x00000000,2020-09-24T10:33:30.608Z,2020-09-24T10:33:30.608Z
...,...,...,...,...,...,...
24674,527,0x0007,1050954605,0x00000000,2020-09-24T11:07:57.354Z,2020-09-24T11:07:57.354Z
24675,528,0x0007,3189550223,0x00000000,2020-09-24T11:07:57.103Z,2020-09-24T11:07:57.103Z
24676,528,0x0007,3190252313,0x00000000,2020-09-24T11:07:57.354Z,2020-09-24T11:07:57.354Z
24677,529,0x0007,1052155289,0x00000000,2020-09-24T11:07:57.102Z,2020-09-24T11:07:57.102Z
24678,529,0x0007,1051540349,0x00000000,2020-09-24T11:07:57.352Z,2020-09-24T11:07:57.352Z

In [12]:
data_st

,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp
0,DiscSize,0x0003,1,0x00000000,2020-09-24T10:32:52.725Z,2020-09-24T10:32:52.725Z
1,DiscSize,0x0003,1,0x00000000,2020-09-24T10:32:53.025Z,2020-09-24T10:32:53.025Z
2,DiscSize,0x0003,1,0x00000000,2020-09-24T10:32:53.325Z,2020-09-24T10:32:53.325Z
3,DiscSize,0x0003,1,0x00000000,2020-09-24T10:32:53.625Z,2020-09-24T10:32:53.625Z
4,DiscSize,0x0003,1,0x00000000,2020-09-24T10:32:53.925Z,2020-09-24T10:32:53.925Z
...,...,...,...,...,...,...
6753,DiscSize,0x0003,2,0x00000000,2020-09-24T11:07:18.525Z,2020-09-24T11:07:18.525Z
6754,DiscSize,0x0003,2,0x00000000,2020-09-24T11:07:18.825Z,2020-09-24T11:07:18.825Z
6755,DiscSize,0x0003,2,0x00000000,2020-09-24T11:07:19.125Z,2020-09-24T11:07:19.125Z
6756,DiscSize,0x0003,2,0x00000000,2020-09-24T11:07:19.425Z,2020-09-24T11:07:19.425Z
6757,DiscSize,0x0003,2,0x00000000,2020-09-24T11:07:19.725Z,2020-09-24T11:07:19.725Z

## Merge Data Sets

In [13]:
data_set = [data_conv, data_gate, data_qc, data_rp, data_st]
data_merge = pd.concat(data_set, keys=['conv', 'gate', 'qc', 'rp', 'store'])
# Sort the data_set by SourceTimeStamp, reset index and delete aux column
data_merge = data_merge.sort_values(by='SourceTimeStamp').reset_index().drop('level_1',1)
#del data_merge['level_1'] #delete aux column

In [14]:
data_merge

,level_0,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp
0,gate,Safe,0x0001,true,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z
1,gate,Speed,0x000b,0,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z
2,gate,Position,0x000b,0.2,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z
3,gate,Safe,0x0001,true,0x00000000,2020-09-24T10:32:41.607Z,2020-09-24T10:32:41.607Z
4,gate,Speed,0x000b,0,0x00000000,2020-09-24T10:32:41.607Z,2020-09-24T10:32:41.607Z
...,...,...,...,...,...,...,...
78757,rp,528,0x0007,3189550223,0x00000000,2020-09-24T11:07:57.103Z,2020-09-24T11:07:57.103Z
78758,rp,527,0x0007,1050966298,0x00000000,2020-09-24T11:07:57.106Z,2020-09-24T11:07:57.106Z
78759,rp,529,0x0007,1051540349,0x00000000,2020-09-24T11:07:57.352Z,2020-09-24T11:07:57.352Z
78760,rp,527,0x0007,1050954605,0x00000000,2020-09-24T11:07:57.354Z,2020-09-24T11:07:57.354Z
78761,rp,528,0x0007,3190252313,0x00000000,2020-09-24T11:07:57.354Z,2020-09-24T11:07:57.354Z

## Export Data to csv

In [15]:
data_merge.to_csv(path_data_save + 'data_merge.csv')
print('The data is saved at ' + path_data_save + 'data_merge.csv')

The data is saved at ../01_Data/200924/use_case1/Processed/data_merge.csv

In [16]:
len(data_merge)

78762

## Determine the starting point of data set

#Based on change of DistanceAbs in Data- Set
var_actual = 0
run_list = [0]
for i in range(len(data_merge)):
    var_previous = var_actual
    if data_merge.at[i,'PrimaryKey'] == 'DistanceAbs':  # if 'PrimaryKey' value = 'DistanceAbs':
        var_actual = data_merge.at[i,'Value'] # value of current DistanceAbs
    if var_previous != var_actual:
        run_list.append(i) #i append to list # This list will tell at how many i contains one sample

In [17]:
# Based on grabbing the white disk
var_actual = 99
disk_actual = 99 # Initial value
run_list = [0]
disk = False
storage_down = False
rob_x = 0
rob_y = 0
rob_z = 0
rob_pos = 0
pos = [0]*(len(data_merge)-2)
for i in range(len(data_merge)-2): # len(data_merge)-2 is considered to avoid border errors
    #var_previous = var_actual
    #rob_pos = fc_rob_pos(i, data_merge) # review robot position
    pos[i] = 0
    if data_merge.at[i,'PrimaryKey'] == 'DiscSize':  # if 'PrimaryKey' value = 'DiskSize':
        disk_previous = disk_actual
        disk_actual = data_merge.at[i,'Value'] # value of current DiskSize
        #print(disk_previous, disk_actual, i)
        if disk_previous != 2 and disk_actual == 2: # Varialbe 0: unkown; 1: Black disk; 2: white disk
            disk = True
            #print('New white disk here ' + str(i))
    if data_merge.at[i,'PrimaryKey'] == '527':  # if 'PrimaryKey' value = 'x coordinate':
        rob_x = data_merge.at[i,'Value'] # value of current 'x coordinate'
        #print('x = ' + str(rob_x) + '--' + str(i))
    if data_merge.at[i,'PrimaryKey'] == '528':  # if 'PrimaryKey' value = 'y coordinate':
        rob_y = data_merge.at[i,'Value'] # value of current 'x coordinate'
        #print('y = ' + str(rob_y) + '--' + str(i))
    if data_merge.at[i,'PrimaryKey'] == '529':  # if 'PrimaryKey' value = 'z coordinate':
        rob_z = data_merge.at[i,'Value'] # value of current 'x coordinate'
        #print('z = ' + str(rob_z) + '--' + str(i))
    if rob_x > 3100000000 and rob_y > 3100000000 and rob_z < 1051200000: #Robot in storage. Picking up the disk
        rob_pos = 1
        pos[i] = 1
        #print('pos 1 - ' + str(i))
    if rob_x < 1052000000 and rob_y > 3100000000 and rob_z < 1052000000 and rob_z > 1051200000 : #Robot in storage. Placing down the disk
        rob_pos = 2
        pos[i] = 2
        #print('pos 2 - ' + str(i))
    #print(rob_pos)
    if rob_pos == 1: # Robot picking up a disk
        storage_down = True
        #print(storage_down,i)  
    if disk == True and storage_down == True:
        #var_actual = rob_pos
        disk = False
        storage_down = False
        run_list.append(i) #i append to list # This list will tell at how many i contains one sample
        #print(i)
    #if var_previous != var_actual:
        #run_list.append(i) #i append to list # This list will tell at how many i contains one sample

In [18]:
print(run_list) # Starting points. 
print(len(run_list))

[0, 1504, 1776, 1949, 2939, 3994, 4933, 5038, 6082, 7032, 7137, 8181, 9225, 10623, 16748, 17698, 17803, 18847, 19891, 20946, 21989, 23042, 24086, 25130, 26080, 26185, 27229, 28178, 28283, 29316, 30277, 30382, 31437, 32481, 33525, 34582, 35626, 36576, 36681, 37736, 38780, 39835, 40868, 41832, 41934, 42978, 44022, 45080, 46124, 47168, 47190, 48223, 49173, 49278, 50311, 51366, 52410, 53360, 53465, 54509, 55553, 56608, 57652, 58710, 59754, 60704, 60798, 61853, 62803, 62908, 63952, 65634, 66575, 67619, 68572, 68674, 69732, 70776, 71726, 71831, 72875, 73919, 74869, 74974, 76018, 76968, 77073, 78116]
88

In [19]:
# data_merge.iloc[list(range(0,3))]

In [20]:
df_robpos = pd.DataFrame(pos,columns=['RobPos']) # Position of robot. 0: not important; 1: Robot in storage. Picking up the disk; 2:Robot in storage. Placing down the disk
data_merge = pd.concat([data_merge, df_robpos], axis=1, sort=False)
data_merge

,level_0,PrimaryKey,DataType,Value,StatusCode,SourceTimeStamp,ServerTimeStamp,RobPos
0,gate,Safe,0x0001,true,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z,0.0
1,gate,Speed,0x000b,0,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z,0.0
2,gate,Position,0x000b,0.2,0x00000000,2020-09-24T10:32:41.307Z,2020-09-24T10:32:41.307Z,0.0
3,gate,Safe,0x0001,true,0x00000000,2020-09-24T10:32:41.607Z,2020-09-24T10:32:41.607Z,0.0
4,gate,Speed,0x000b,0,0x00000000,2020-09-24T10:32:41.607Z,2020-09-24T10:32:41.607Z,0.0
...,...,...,...,...,...,...,...,...
78757,rp,528,0x0007,3189550223,0x00000000,2020-09-24T11:07:57.103Z,2020-09-24T11:07:57.103Z,0.0
78758,rp,527,0x0007,1050966298,0x00000000,2020-09-24T11:07:57.106Z,2020-09-24T11:07:57.106Z,0.0
78759,rp,529,0x0007,1051540349,0x00000000,2020-09-24T11:07:57.352Z,2020-09-24T11:07:57.352Z,2.0
78760,rp,527,0x0007,1050954605,0x00000000,2020-09-24T11:07:57.354Z,2020-09-24T11:07:57.354Z,NaN
78761,rp,528,0x0007,3190252313,0x00000000,2020-09-24T11:07:57.354Z,2020-09-24T11:07:57.354Z,NaN

The list contains the point i when the value is different. To consider the point where the value remains, consider i-1

In [21]:
d = {} # Dictionary that holds the sub-data-sets given by the starting point
for i in range(len(run_list)-1): # Ignores the last value (set of values)
    list_range = list(range(run_list[i],run_list[i+1]))
    d['df{0}'.format(i)] = data_merge.iloc[list_range]
    
print('Dictionary lenght is:' + str(len(d)))

Dictionary lenght is:87

## Assure conv_speed per sample

In [22]:
conv_1 = 0
conv_2 = 0
conv_3 = 0
conv1 = False
conv2 = False
conv3 = False
for j in range(len(d)): # as many samples saved in dictionary
    df = d['df'+ str(j)]
    for i in range(len(df)): # as many row in the dataFrame
        #print(df.iat[i,1])
        if df.iat[i,1] == '27': # conv1
            conv_1 = df.iat[i,3]
            conv1 = True # the value shows at least once in the data set
        if df.iat[i,1] == '28': # conv2
            conv_2 = df.iat[i,3]
            conv2 = True
        if df.iat[i,1] == '29': # conv3
            conv_3 = df.iat[i,3]
            conv3 = True
    if conv1 == False: # The value did not occur in this sample. Copy value from previous samples into this one
        dic = {'PrimaryKey' : '27', 'Value': str(conv_1)}
        df.loc[len(df)+1,'PrimaryKey'] = '27'
        df.loc[len(df),'Value'] = str(conv_1)
        df.loc[len(df),'DataType'] = 'NA'
        df.loc[len(df),'StatusCode'] = 'NA'
        df.loc[len(df),'SourceTimeStamp'] = 'NA'
        df.loc[len(df),'ServerTimeStamp'] = 'NA'
    if conv2 == False:
        dic = {'PrimaryKey' : '27', 'Value': str(conv_2)}
        df.loc[len(df)+1,'PrimaryKey'] = '28'
        df.loc[len(df),'Value'] = str(conv_2)
        df.loc[len(df),'DataType'] = 'NA'
        df.loc[len(df),'StatusCode'] = 'NA'
        df.loc[len(df),'SourceTimeStamp'] = 'NA'
        df.loc[len(df),'ServerTimeStamp'] = 'NA'
    if conv3 == False:
        dic = {'PrimaryKey' : '27', 'Value': str(conv_3)}
        df.loc[len(df)+1,'PrimaryKey'] = '29'
        df.loc[len(df),'Value'] = str(conv_3)
        df.loc[len(df),'DataType'] = 'NA'
        df.loc[len(df),'StatusCode'] = 'NA'
        df.loc[len(df),'SourceTimeStamp'] = 'NA'
        df.loc[len(df),'ServerTimeStamp'] = 'NA'
   
    conv1 = False # reset conv for the next round
    conv2 = False
    conv3 = False
print(conv_1)
print(conv_2)
print(conv_3)

<ipython-input-22-c66d3a04daa1>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[len(df)+1,'PrimaryKey'] = '27'

300
363
380

## Export individual data-sample to .csv

In [23]:
for i in range(len(d)):
    if i > 0: # always ignore the first sample due to data-acquisition misalligment
        d['df' + str(i)].to_csv(path_sample_save + 'sample_' + str(i) + '.csv')
print('The data is saved at ' + path_sample_save + 'sample_x.csv')

The data is saved at ../01_Data/200924/use_case1/Processed/Samples/sample_x.csv

## Testing area

In [24]:
#d['df67']

In [25]:
# list_range = list(range(run_list[0],run_list[1]))
# print(list_range)

In [26]:
# data_merge.iloc[list_range]

In [27]:
# data_rp.loc[:, 'PrimaryKey'] = '529_z'
# data_rp

In [28]:
# %matplotlib notebook 
# data_gate.head(400).plot(x='SourceTimeStamp', y= 'Value')
# plt.xticks(rotation=45)

In [29]:
# %matplotlib notebook 
# data_rp.head(200).plot( y= 'Value')
# plt.xticks(rotation=45)